java_library(
    name = "commons-configuration",
    exports = [
        "//external:jar/commons-configuration/commons-configuration"
    ],
    runtime_deps = [
        "//dependencies/artifacts/commons-lang:commons-lang",
        "//dependencies/artifacts/commons-logging:commons-logging"
    ],
    visibility = [
        "//dependencies/artifacts:__subpackages__"
    ]
)


