java_library(
    name = "commons-lang3",
    exports = [
        "//external:jar/org/apache/commons/commons-lang3"
    ],
    visibility = [
        "//dependencies/artifacts:__subpackages__"
    ]
)



java_library(
    name = "commons-math3",
    exports = [
        "//external:jar/org/apache/commons/commons-math3"
    ],
    visibility = [
        "//dependencies/artifacts:__subpackages__"
    ]
)



java_library(
    name = "commons-text",
    exports = [
        "//external:jar/org/apache/commons/commons-text"
    ],
    visibility = [
        "//dependencies/artifacts:__subpackages__"
    ]
)


