java_library(
    name = "jettison",
    exports = [
        "//external:jar/org/codehaus/jettison/jettison"
    ],
    runtime_deps = [
        "//dependencies/artifacts/stax:stax-api"
    ],
    visibility = [
        "//dependencies/artifacts:__subpackages__"
    ]
)


