java_library(
    name = "org-apache-servicemix-bundles-commons-csv",
    exports = [
        "//external:jar/org/apache/servicemix/bundles/org-apache-servicemix-bundles-commons-csv"
    ],
    visibility = [
        "//dependencies/artifacts:__subpackages__"
    ]
)


