java_library(
    name = "dom4j",
    exports = [
        "//external:jar/dom4j/dom4j"
    ],
    runtime_deps = [
        "//dependencies/artifacts/xml-apis:xml-apis"
    ],
    visibility = [
        "//dependencies/artifacts:__subpackages__"
    ]
)


