java_library(
    name = "commons-collections",
    exports = [
        "//external:jar/commons-collections/commons-collections"
    ],
    visibility = [
        "//dependencies/artifacts:__subpackages__"
    ]
)


