java_library(
    name = "commons-logging",
    exports = [
        "//external:jar/commons-logging/commons-logging"
    ],
    visibility = [
        "//dependencies/artifacts:__subpackages__"
    ]
)


